TERMINAL=(
	git
	foot
	bat
	man
	yazi
	exiftool
	fastfetch
    neovim
    tree-sitter-cli # neovim plugin dependency
    ripgrep # neovim plugin dependency
)

TOOLS=(
	ly
	bemenu
	wl-clipboard
	grim
	slurp
    satty
	wbg
	dunst
    bluetui
    swaylock
    clipse
)

FILE_MANAGEMENT=(
	yazi
	ark
	rar
	tar
    unzip
    thunar
)

INTERNET=(
	firefox
	chromium
)

IMAGE=(
    imv
	imagemagick
	gimp
    tumbler
)

VIDEO=(
	wayland
	wayland-protocols
    xwayland-satellite
    xdg-desktop-portal-wlr
	wlroots0.19
    xorg-xrdb
	ffmpeg
    ffmpegthumbnailer
	mpv
    kdenlive
)

AUDIO=(
	pulsemixer
	pipewire-pulse
	pipewire-alsa
	pipewire-jack
	lib32-pipewire
	lib32-libpulse
)

MUSIC=(
	mpd
	mpc
	rmpc
	songrec
)
