TERMINAL=(
	git
	foot
	bat
	man
	yazi
	neovim
	exiftool
	fastfetch
)

TOOLS=(
	ly
	bemenu
	wl-clipboard
	grim
	slurp
	wbg
	dunst
    bluetui
    swaylock
    clipse
)

FILE_MANAGEMENT=(
	yazi
	ark
	rar
	tar
    unzip
    thunar
)

INTERNET=(
	firefox
	chromium
)

IMAGE=(
    imv
	imagemagick
	gimp
)

VIDEO=(
	wayland
	wayland-protocols
    xwayland-satellite
	wlroots0.19
    xorg-xrdb
	ffmpeg
	mpv
    kdenlive
)

AUDIO=(
	pulsemixer
	pipewire-pulse
	pipewire-alsa
	pipewire-jack
	lib32-pipewire
	lib32-libpulse
)

MUSIC=(
	mpd
	mpc
	rmpc
	songrec
)
