TERMINAL=(
	git
	foot
	bat
	man
	yazi
	neovim
	exiftool
	fastfetch
)

TOOLS=(
	ly
	wmenu
	wl-clipboard
	grim
	slurp
	wbg
)

FILE_MANAGEMENT=(
	yazi
	thunar
	ark
	rar
	tar
	zathura
	zathura-pdf-mupdf
)

INTERNET=(
	firefox
	qutebrowser
	chromium
)

IMAGE=(
	imagemagick
	gimp
)

VIDEO=(
	wayland
	wayland-protocols
	wlroots0.19
	ffmpeg
	mpv
)

AUDIO=(
	pulsemixer
	pipewire-pulse
	pipewire-alsa
	pipewire-jack
	lib32-pipewire
	lib32-libpulse
)

MUSIC=(
	mpd
	mpc
	rmpc
	songrec
)
