# ~/.config/starship.toml
# https://starship.rs

format = """
[ ヾ•ω•`o ](bg:#171a1d fg:#959da5)\
[](bg:#171a1d fg:#171a1d)\
$directory\
[](fg:#171a1d bg:#24292e)\
$git_branch\
$git_status\
[](fg:#24292e bg:#171a1d)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#171a1d bg:#24292e)\
$time\
[ ](fg:#24292e)\
\n$character"""

###

[directory]
style = "fg:#e3e5e5 bg:#171a1d"
format = "[[ $path ](fg:#008b8b bg:#171a1d)]($style)"
truncation_length = 3
truncation_symbol = "…/"

###

[git_branch]
symbol = ""
style = "bg:#24292e"
format = '[[ $symbol $branch ](fg:#ffab70 bg:#24292e)]($style)'

[git_status]
style = "bg:#24292e"
format = '[[($all_status$ahead_behind )](fg:#ffab70 bg:#24292e)]($style)'

###

[nodejs]
symbol = ""
style = "bg:#171a1d"
format = '[[ $symbol ($version) ](fg:#85e89d bg:#171a1d)]($style)'

[rust]
symbol = ""
style = "bg:#171a1d"
format = '[[ $symbol ($version) ](fg:#85e89d bg:#171a1d)]($style)'

[golang]
symbol = ""
style = "bg:#171a1d"
format = '[[ $symbol ($version) ](fg:#85e89d bg:#171a1d)]($style)'

[php]
symbol = ""
style = "bg:#171a1d"
format = '[[ $symbol ($version) ](fg:#85e89d bg:#171a1d)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#24292e"
format = '[[  $time ](fg:#959da5 bg:#24292e)]($style)'