# More option see https://github.com/DreamMaoMao/mango/wiki/

include conf.d/input.conf
include conf.d/layouts.conf
include conf.d/appearance.conf
include conf.d/rules.conf
include conf.d/keybinds.conf
include conf.d/autostart.conf
