# More option see https://github.com/DreamMaoMao/mango/wiki/

source=./conf.d/input.conf
source=./conf.d/layouts.conf
source=./conf.d/appearance.conf
source=./conf.d/monitors.conf
source=./conf.d/rules.conf
source=./conf.d/keybinds.conf
source=./conf.d/autostart.conf
