[window]
opacity = 0.75
padding.x = 0
padding.y = 0
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
size = 10
normal.family = "Hack Nerd Font Mono"
bold.family = "Hack Nerd Font Mono"
italic.family = "Hack Nerd Font Mono"
bold_italic.family = "Hack Nerd Font Mono"

[colors.primary]
foreground = "#dddddd"
background = "#000000"

[colors.normal]
black = "#000000"
red = "{{color1}}"
green = "{{color2}}"
yellow = "{{color3}}"
blue = "{{color4}}"
magenta = "{{color5}}"
cyan = "{{color6}}"
white = "{{color7}}"

[colors.bright]
black = "{{color0}}"
red = "{{color9}}"
green = "{{color10}}"
yellow = "{{color11}}"
blue = "{{color12}}"
magenta = "{{color13}}"
cyan = "{{color14}}"
white = "#ffffff"
