#!/bin/env sh

source "$HOME/.cache/wallust/colors"
if gum confirm "Reiniciar o Spotify para aplicar o tema do wallust?" --prompt.foreground="#$WALLUST_COLOR3" --selected.background="#$WALLUST_BACKGROUND"; then
    spicetify apply
    exit    
elif [ $? -eq 130 ]; then
    echo ":: Tema do Spotify não atualizado."
    sleep 0.5
    exit 130
else
    echo ":: Tema do Spotify não atualizado."
    sleep 0.5
    exit
fi
