env = NOTES_DIR,$HOME/Documents/caderninho

env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=QT_WAYLAND_FORCE_DPI,125

exec-once=echo "Xft.dpi: 125" | xrdb -merge
exec-once=gsettings set org.gnome.desktop.interface text-scaling-factor 1.25

exec-once=wbg -s $HOME/.dotfiles/wallpapers/araruama-2d5a27.jpg
exec-once=clipse -listen
exec-once=mpdscribble
