# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# Close, Exit and Reload Config
bind=super,c,killclient
bind=super+shift,c,killclient,force
bind=super+alt,escape,quit
bind=super+shift,escape,reload_config
bind=super,escape,spawn,$HOME/.local/bin/powermenu

# Applications
bind=super,r,spawn,$HOME/.local/bin/app-launcher
bind=super,q,spawn,foot
bind=super,b,spawn,firefox
bind=super,e,spawn,thunar
bind=super+shift,f1,spawn,foot -a pulsemixer -e pulsemixer
bind=super+ctrl,f1,spawn,foot -a bluetui -e bluetui
bind=super+alt,f1,spawn,foot -a nmtui -e nmtui
bind=super,v,spawn_shell,killall clipse; foot -a clipse -e clipse

# Switch Window Focus
bind=super,tab,focusstack,next
bind=super,left,focusdir,left
bind=super,right,focusdir,right
bind=super,up,focusdir,up
bind=super,down,focusdir,down

# Swap Window
bind=super+ctrl,up,exchange_client,up
bind=super+ctrl,down,exchange_client,down
bind=super+ctrl,left,exchange_client,left
bind=super+ctrl,right,exchange_client,right

# Switch Window Status
bind=super,x,togglefloating
bind=super,f,togglefullscreen
bind=super+shift,f,togglemaximizescreen
bind=super+alt,f,togglefakefullscreen
bind=super,a,centerwin
bind=super,space,togglejump
bind=super,i,minimized
bind=super+shift,i,restore_minimized
bind=super,g,toggleglobal
bind=super,o,toggleoverlay
bind=super,s,toggle_scratchpad

# Switch Layout
bind=super,n,switch_layout

# Dwindle Layout (manual split mode)
bind=super,z,dwindle_toggle_split_direction

# Scroller Layout
bind=super+ctrl,z,switch_proportion_preset,
bind=super+ctrl,x,set_proportion,1.0
bind=super+ctrl+alt,left,scroller_stack,left
bind=super+ctrl+alt,right,scroller_stack,right
bind=super+ctrl+alt,up,scroller_stack,up
bind=super+ctrl+alt,down,scroller_stack,down

# Tag Switch
bind=super+alt,left,viewtoleft_have_client,0
bind=super+alt,right,viewtoright_have_client,0
bind=super+ctrl+alt,left,viewtoleft,0
bind=super+ctrl+alt,right,viewtoright,0
bind=super+shift+alt,left,tagtoleft,0
bind=super+shift+alt,right,tagtoright,0

bind=super,1,view,1,0
bind=super,2,view,2,0
bind=super,3,view,3,0
bind=super,4,view,4,0
bind=super,5,view,5,0
bind=super,6,view,6,0
bind=super,7,view,7,0
bind=super,8,view,8,0
bind=super,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
bind=super+shift,1,tag,1,0
bind=super+shift,2,tag,2,0
bind=super+shift,3,tag,3,0
bind=super+shift,4,tag,4,0
bind=super+shift,5,tag,5,0
bind=super+shift,6,tag,6,0
bind=super+shift,7,tag,7,0
bind=super+shift,8,tag,8,0
bind=super+shift,9,tag,9,0

# Monitor Switch
bind=alt+shift,left,focusmon,left
bind=alt+shift,right,focusmon,right
bind=super+alt,left,tagmon,left
bind=super+alt,right,tagmon,right

# Gaps
# bind=alt+shift,x,incgaps,1
# bind=alt+shift,z,incgaps,-1
# bind=alt+shift,r,togglegaps

# Move Window
bind=super+ctrl+shift,up,movewin,+0,-50
bind=super+ctrl+shift,down,movewin,+0,+50
bind=super+ctrl+shift,left,movewin,-50,+0
bind=super+ctrl+shift,right,movewin,+50,+0

# Resize Window
bind=super+shift,up,resizewin,+0,-50
bind=super+shift,down,resizewin,+0,+50
bind=super+shift,left,resizewin,-50,+0
bind=super+shift,right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=super,btn_left,moveresize,curmove
mousebind=super,btn_middle,togglemaximizescreen,0
mousebind=super,btn_right,moveresize,curresize

# Axis Bindings
axisbind=super,up,viewtoleft_have_client
axisbind=super,down,viewtoright_have_client
