# Window Rule
windowrule=isfloating:1,appid:wmenu
windowrule=isfloating:1,width:800,height:600,appid:pulsemixer
windowrule=isfloating:1,width:800,height:600,appid:bluetui
windowrule=isfloating:1,width:800,height:600,appid:nmtui
windowrule=isfloating:1,width:800,height:800,appid:clipse

# Layer Rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
