#!/usr/bin/sh

# NOTE: KAOMOJIS file taken from https://git.sr.ht/~pkal/insert-kaomoji
# convenient for me since i also use this emacs package

moji_dir=$(dirname "$0")
moji_path="$moji_dir/kaomojis"
categories=$(grep -o -E '\<[A-Z][a-z]{2,}\>' "$moji_path")
select_random="Control+Return"

show_menu() {
  # force monospace font to not get those fields messy
  category=$(echo -e "$categories" |
    rofi -dmenu -i -theme style.rasi -theme-str '#entry { placeholder: "Procurar..."; }' \
      -kb-custom-1 "$select_random" \
      -kb-accept-custom "" \
      -theme-str '* { font: "Hack Mono Nerd Font 10"; }')

  rofi_exit=$?

  [ $rofi_exit -eq 1 ] && exit

  line=$(grep "$category" "$moji_path")
  # trim one specitl sign from the end
  line="${line%*}"
  # trim another special sign from the beginning, including category names
  line="${line#*}"

  kaomojis=$(echo "$line" | tr '' '\n' | awk '{ print length, $0 }' |
    sort -n | cut -d' ' -f 2-)

  kaomojis="$kaomojis"$'\n'"voltar"

  case $rofi_exit in
    10) selection=$(echo "$kaomojis" | head -n -1 | shuf -n 1) ;;
    0)
      selection=$(echo "$kaomojis" |
        rofi -dmenu -i -theme style.rasi)
      ;;
    *) exit ;;
  esac

  if [ "$selection" = "voltar" ]; then
    show_menu
  else
    wl-copy "$selection"
  fi
}

show_menu

exit 0
