#!/bin/bash
# script para instalar todas as fontes do diretório atual
# autor: https://github.com/miguelgargallo/install-arch-fonts

# exibir "Fontes" através do figlet
printf "$(hexToAnsi "$WALLUST_COLOR3")"; figlet "Fontes"
printf "\033[0m"
echo

# definir diretório atual
FONT_DIR=$(pwd)

# conferir se a pasta de fontes existe
if [ ! -d "$FONT_DIR" ]; then
    echo ":: O diretório desejado não existe."
    exit 1
fi

# copiar todas as fontes para a pasta de fontes do sistema
sudo cp -r -v "$FONT_DIR"/*.otf /usr/share/fonts/;
sudo cp -r -v "$FONT_DIR"/*.ttf /usr/share/fonts/;
echo

# atualizar cache das fontes
sudo fc-cache -f -v;
echo

echo ":: Fontes instaladas com sucesso."

