#!/bin/env sh

# autor: https://github.com/miguelgargallo/install-arch-fonts
# script para instalar todas as fontes do diretório atual

# conferir se o usuário está rodando como root
if [[ $EUID -ne 0 ]]; then
    echo ":: Esse script deve ser executado como root."
    exit 1
fi

# definir diretório atual
FONT_DIR=$(pwd)

# conferir se a pasta de fontes existe
if [ ! -d "$FONT_DIR" ]; then
    echo ":: O diretório desejado não existe."
    exit 1
fi

# copiar todas as fontes para a pasta de fontes do sistema
cp -r $FONT_DIR/*.otf /usr/share/fonts/;
cp -r $FONT_DIR/*.ttf /usr/share/fonts/;

# atualizar cache das fontes
fc-cache -f -v;

echo ":: Fontes instaladas com sucesso."

