#!/bin/env sh

source ~/.venv/venv/bin/activate

SONG_ARTIST=$(mpc current -f %artist%)
SONG_TITLE=$(mpc current -f %title%)

SONG_PATH="$HOME/Music/$(mpc current -f %file% | cut -d '/' -f1,2)"
SONG_PATH_CORRECTED="$HOME/Music/$(mpc current -f %file% | cut -d '/' -f1,2 | sed 's/ /\\ /g' | sed 's/(/\\(/g' | sed 's/)/\\)/g')"

SONG_FILENAME=$(mpc current -f %file% | cut -d '/' -f3 | cut -d '.' -f1)
SONG_FILENAME_CORRECTED=$(mpc current -f %file% | cut -d '/' -f3 | cut -d '.' -f1 | sed 's/ /\\ /g' | sed 's/(/\\(/g' | sed 's/)/\\)/g')
SONG_EXTENSION=$(mpc current -f %file% | cut -d '/' -f3 | cut -d '.' -f2)

if [[ $(mpc current) ]]; then
    clear
    echo
    printf "$(hexToAnsi "$WALLUST_COLOR3")"; echo ":: $SONG_ARTIST - $SONG_TITLE"
    printf "\033[0m"
    echo
    if [ -s "$SONG_PATH/$SONG_FILENAME.lrc" ]; then
        sleep 0.25
        cat "$SONG_PATH/$SONG_FILENAME.lrc"
        echo
    else
        # busca pela letra da musica sem exibir o output
        syncedlyrics -o "$SONG_PATH/$SONG_FILENAME.lrc" "$SONG_ARTIST - $SONG_TITLE" > /dev/null 2>&1
        
        # insere a letra no arquivo sem exibir o output
        eyeD3 --quiet --add-lyrics="$SONG_PATH/$SONG_FILENAME.lrc" "$SONG_PATH/$SONG_FILENAME.$SONG_EXTENSION" > /dev/null 2>&1

        if [ -s "$SONG_PATH/$SONG_FILENAME.lrc" ]; then
            sleep 0.25
            cat "$SONG_PATH/$SONG_FILENAME.lrc"
            echo
        else
            echo ":: Letra da música não encontrada."
        fi
    fi
else
    echo ":: O mpd não está em execução ou nenhuma música está tocando."
fi
