#!/bin/bash
# script para automatizar a copia entre arquivos do memory card para computador e vice-versa.

printf "$(hexToAnsi "$WALLUST_COLOR3")"; figlet "Memcard"
printf '\033[0m'
echo

COPY="$(gum choose "MEMCARD -> PC" "PC -> MEMCARD" "Sair" --cursor.foreground="#$WALLUST_COLOR3" --cursor.background="#$WALLUST_BACKGROUND" --item.foreground="#$WALLUST_FOREGROUND")"

if [ -d /run/media/$USER/EVAMEMCARD ]; then
    :
else
    echo
    echo ":: Operação cancelada ou diretório do memory card não encontrado."
    sleep 1
    exit
fi

MEMCARD_DIR="/run/media/$USER/EVAMEMCARD/Android/data/com.retroarch/files/"
RA_DIR="$HOME/Games/RetroArch/RetroArch.AppImage.home/.config/retroarch/"

if [ "$COPY" == "MEMCARD -> PC" ]; then
    echo ":: Copiando arquivos do memory card para o computador local."
    sleep 1.5
    mkdir -p $RA_DIR
    cp -rv $MEMCARD_DIR/saves $RA_DIR
    exit
elif [ "$COPY" == "PC -> MEMCARD" ]; then
    echo ":: Copiando arquivos do computador local para o memory card."
    sleep 1.5
    mkdir -p $MEMCARD_DIR
    cp -rv $RA_DIR/saves $MEMCARD_DIR
    cp -rv
    exit
elif [ "$COPY" == "Cancelar" ]; then
    echo
    echo ":: Cópia cancelada"
    sleep 1
    exit
else
    echo
    echo ":: Cópia cancelada."
    sleep 1
    exit
fi

