#!/bin/env sh

# script para montar a partição ntfs (não uso com frequência)

# exibir "mountNtfs" através do figlet
printf "$(hexToAnsi "$WALLUST_COLOR3")"; figlet "mountNtfs"
printf "\033[0m"
echo

if [ -z $1 ]; then
    if mountpoint -q /eva03/public/; then
        sudo umount /dev/sdc2
        echo ":: Nenhum parâmetro especificado. Partição /dev/sdc2 desmontada."
    else
        sudo mount /dev/sdc2 /eva03/public/
        echo ":: Nenhum parâmetro especificado. Partição /dev/sdc2 montada em /eva03/public"
    fi
elif [ $1 == "--help" ]; then
    echo ":: Comandos:"
    echo "mountNtfs 1 # montar partição"
    echo "mountNtfs 0 # desmontar partição"
    exit 1
elif [ $1 == 1 ]; then
    sudo mount /dev/sdc2 /eva03/public/
    echo ":: Partição /dev/sdc2 montada em /eva03/public"
elif [ $1 == 0 ]; then
    sudo umount /dev/sdc2
    echo ":: Partição /dev/sdc2 desmontada."
fi
