#!/bin/bash
# script para desativar ou ativar a conexão com a internet alternadamente

if nmcli networking connectivity | grep -q "none"; then
    echo "Networking is currently off. Turning it on..."
    nmcli networking on
else
    echo "Networking is currently on. Turning it off..."
    nmcli networking off
fi
