#!/bin/bash
# script para desativar ou ativar a conexão com a internet alternadamente

DEVICE=$(nmcli device | grep ethernet | awk '{print $1}')
STATUS=$(nmcli device status | grep "$DEVICE" | awk '{print $3}')
if [ "$STATUS" = "connected" ]; then
    nmcli device disconnect "$DEVICE"
else
    nmcli device connect "$DEVICE"
fi

