#!/bin/bash
# script para montar a partição ntfs (não uso com frequência)

# exibir "mountNtfs" através do figlet
printf "$(hexToAnsi "$WALLUST_COLOR3")"; figlet "mountNtfs"
echo

NTFS_PART="/dev/sdc2"
MOUNT_POINT="/run/ntfs"

printf "$(hexToAnsi "$WALLUST_COLOR0")"
echo "Partição NTFS atual: $NTFS_PART"
echo "Ponto de montagem: $MOUNT_POINT"
printf "\033[0m"
echo

if [ ! -d "$MOUNT_POINT" ]; then
    sudo mkdir -p "$MOUNT_POINT"
fi

OPTION="$(gum choose "Montar partição NTFS" "Desmontar partição NTFS" "Sair" --cursor.foreground="#$WALLUST_COLOR3" --cursor.background="#$WALLUST_BACKGROUND" --item.foreground="#$WALLUST_FOREGROUND")"

if [ "$OPTION" == "Montar partição NTFS" ]; then
    if df -h | grep "$NTFS_PART" > /dev/null; then
        echo ":: Partição $NTFS_PART já encontra-se montada. Nenhuma alteração foi feita."
    else
        sudo mount $NTFS_PART $MOUNT_POINT
        echo ":: Partição $NTFS_PART montada em $MOUNT_POINT"
    fi
    exit
elif [ "$OPTION" == "Desmontar partição NTFS" ]; then
    if df -h | grep "$NTFS_PART" > /dev/null; then
        sudo umount $NTFS_PART
        echo ":: Partição $NTFS_PART desmontada."
    else
        echo ":: Partição $NTFS_PART já encontra-se desmontada. Nenhuma alteração foi feita."
    fi
    exit
elif [ "$OPTION" == "Cancelar" ]; then
    echo
    echo ":: Operação cancelada. Nenhuma alteração foi feita."
    sleep 1
    exit
else
    echo
    echo ":: Operação cancelada. Nenhuma alteração foi feita."
    sleep 1
    exit
fi

