#!/bin/env sh

# script para montar a partição ntfs (não uso com frequência)

# exibir "mountNtfs" através do figlet
printf "$(hexToAnsi "$WALLUST_COLOR3")"; figlet "mountNtfs"
echo

NTFS_PART="/dev/sdc2"
MOUNT_POINT="/run/ntfs"

printf "$(hexToAnsi "$WALLUST_COLOR0")"
echo "Partição NTFS atual: $NTFS_PART"
echo "Ponto de montagem: $MOUNT_POINT"
printf "\033[0m"
echo

OPTION="$(gum choose "Montar partição NTFS" "Desmontar partição NTFS" "Sair" --cursor.foreground="#$WALLUST_COLOR3" --cursor.background="#$WALLUST_BACKGROUND" --item.foreground="#$WALLUST_FOREGROUND")"

if [ "$OPTION" == "Montar partição NTFS" ]; then
    sudo mount $NTFS_PART $MOUNT_POINT
    echo ":: Partição $NTFS_PART montada em $MOUNT_POINT"
    exit
elif [ "$OPTION" == "Desmontar partição NTFS" ]; then
    sudo umount $NTFS_PART
    echo ":: Partição $NTFS_PART desmontada."
    exit
elif [ "$OPTION" == "Cancelar" ]; then
    echo
    echo ":: Montagem/desmontagem cancelada. Nenhuma alteração foi feita."
    sleep 1
    exit
else
    echo
    echo ":: Montagem/desmontagem cancelada. Nenhuma alteração foi feita."
    sleep 1
    exit
fi
