#!/bin/bash
# script para exibir os pacotes instalados em ordem cronológica

# esperar 1 segundo e limpar a tela
sleep 1
clear

# exibir "Pacotes por data" através do figlet
printf "$(hextoansi "$WALLUST_COLOR3")"; figlet "Pacotes por data"
printf "\033[0m"
echo

for i in $(pacman -Qq)
do
    grep "\[ALPM\] installed $i" /var/log/pacman.log
done | \
    sort -u | \
    sed -e 's/\[ALPM\] installed //' -e 's/(.*$//'
bash

