#!/bin/env sh

# script para exibir os signals do linux

# exibir "Signals" através do figlet
printf "$(hexToAnsi "$WALLUST_COLOR3")"; figlet "Signals"
printf "\033[0m"
echo

echo "1     SIGHUP        Hangup (POSIX)"
echo "2     SIGINT	    Terminal interrupt (ANSI)"
echo "3     SIGQUIT	    Terminal quit (POSIX)"
echo "4     SIGILL	    Illegal instruction (ANSI)"
echo "5     SIGTRAP	    Trace trap (POSIX)"
echo "6     SIGIOT	    IOT Trap (4.2 BSD)"
echo "7     SIGBUS	    BUS error (4.2 BSD)"
echo "8     SIGFPE	    Floating point exception (ANSI)"
echo "9     SIGKILL	    Kill(can't be caught or ignored) (POSIX)"
echo "10    SIGUSR1	    User defined signal 1 (POSIX)"
echo "11    SIGSEGV	    Invalid memory segment access (ANSI)"
echo "12    SIGUSR2	    User defined signal 2 (POSIX)"
echo "13    SIGPIPE	    Write on a pipe with no reader, Broken pipe (POSIX)"
echo "14    SIGALRM	    Alarm clock (POSIX)"
echo "15    SIGTERM	    Termination (ANSI)"
echo "16    SIGSTKFLT	    Stack fault"
echo "17    SIGCHLD	    Child process has stopped or exited, changed (POSIX)"
echo "18    SIGCONT	    Continue executing, if stopped (POSIX)"
echo "19    SIGSTOP	    Stop executing(can't be caught or ignored) (POSIX)"
echo "20    SIGTSTP	    Terminal stop signal (POSIX)"
echo "21    SIGTTIN	    Background process trying to read, from TTY (POSIX)"
echo "22    SIGTTOU	    Background process trying to write, to TTY (POSIX)"
echo "23    SIGURG	    Urgent condition on socket (4.2 BSD)"
echo "24    SIGXCPU	    CPU limit exceeded (4.2 BSD)"
echo "25    SIGXFSZ	    File size limit exceeded (4.2 BSD)"
echo "26    SIGVTALRM	    Virtual alarm clock (4.2 BSD)"
echo "27    SIGPROF	    Profiling alarm clock (4.2 BSD)"
echo "28    SIGWINCH	    Window size change (4.3 BSD, Sun)"
echo "29    SIGIO	    I/O now possible (4.2 BSD)"
echo "30    SIGPWR	    Power failure restart (System V)"
