#!/bin/env sh

# script para testar os lados stereo do fone de ouvido/auto-falante

# exibir "Stereo test" através do figlet
printf "$(hexToAnsi "$WALLUST_COLOR3")"; figlet "Stereo test"
echo

# executar teste através do mpv
mpv $HOME/.scripts/src/stereo-test.mp3

echo
echo ":: Teste finalizado."
