#!/bin/bash
# script feito para automatizar a troca de wallpaper e sua sincronização com wallust

DIR="$HOME/.dotfiles/wallpapers"
WALL=$(echo "$(ls $DIR)" | rofi -dmenu -theme "$HOME/.config/rofi/style.rasi" -show-icons)
WALL_EXT=$(echo $WALL | cut -d '/' -f3 | rev | cut -d '.' -f1 | rev)

if [ -n "$WALL" ]; then
    WALL_PATH="$DIR/$WALL"
    echo "$WALL_PATH"
else
    echo ":: Nenhum papel de parede selecionado. Saindo..."
    exit 0
fi

# hyprpaper
HYPRPAPER="$HOME/.config/hypr/hyprpaper.conf"
figlet "hyprpaper" > $HYPRPAPER
sed "1,6 s/^/# /" $HYPRPAPER > $HYPRPAPER.TMP
mv $HYPRPAPER.TMP $HYPRPAPER
echo "" >> $HYPRPAPER
echo "preload = $WALL_PATH" >> $HYPRPAPER
echo "wallpaper =,$WALL_PATH" >>  $HYPRPAPER
hyprctl hyprpaper preload "$WALL_PATH"
hyprctl hyprpaper wallpaper "HDMI-A-1,$WALL_PATH"

# wallust
wallust -s run "$WALL_PATH"
pywalfox update
swaync-client -rs

# blur wallpaper
WALLUST="$HOME/.cache/wallust"
cp -r $WALL_PATH $WALLUST/wallpaper.$WALL_EXT
magick "$WALLUST/wallpaper.$WALL_EXT" -blur 0x8 "$WALLUST/wallpaper-blurred.$WALL_EXT"
WALL_BLUR="$WALLUST/wallpaper-blurred.$WALL_EXT"

# hyprlock
HYPRLOCK="$HOME/.config/hypr/hyprlock.conf"
WALL_SED=$(printf '%s\n' "$WALL_BLUR" | sed 's/[\/&]/\\&/g')
sed "10s/.*/    path = $WALL_SED/" $HYPRLOCK > $HYPRLOCK.TMP
mv $HYPRLOCK.TMP $HYPRLOCK

ps -C spotify > /dev/null
if [ $? = 0 ]; then
    kitty --app-id confirm ~/.scripts/src/wallustify
    exit
else
    spicetify apply
    exit
fi

