#!/bin/bash
# script feito para automatizar a troca de wallpaper e sua sincronização com wallust

DIR="$HOME/.dotfiles/wallpapers"
WALL=$(echo "$(ls $DIR)" | rofi -dmenu -theme "$HOME/.config/rofi/style.rasi" -show-icons)
WALL_EXT=$(echo $WALL | cut -d '/' -f3 | rev | cut -d '.' -f1 | rev)

if [ -n "$WALL" ]; then
    WALL_PATH="$DIR/$WALL"
    echo "$WALL_PATH"
else
    echo ":: Nenhum papel de parede selecionado. Saindo..."
    exit 0
fi

# swaybg
SWAYBG="$HOME/.config/sway/config.d/monitors.conf"
sed -i '$d' $SWAYBG
echo "output * bg $WALL_PATH fill" >> $SWAYBG
swaymsg reload

# wallust
wallust -s run "$WALL_PATH"
pywalfox update
swaync-client -rs

# swaylock
SWAYLOCK="$HOME/.config/swaylock/config"
WALL_SED=$(printf '%s\n' "$WALL_PATH" | sed 's/[\/&]/\\&/g')
sed -i "1s/.*/image=$WALL_SED/" $SWAYLOCK

ps -C spotify > /dev/null
if [ $? = 0 ]; then
    alacritty --app-id confirm ~/.scripts/src/wallustify
    exit
else
    spicetify apply
    exit
fi

